# Generated by Django 6.0.1 on 2026-01-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('mode', models.CharField(choices=[('MJ', 'Multijoueur'), ('BR', 'Battle Royale')], max_length=2)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('recompense', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantTournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejoint_le', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profils.profiljoueur')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournois.tournoi')),
            ],
        ),
    ]
