# Generated by Django 5.1.2 on 2026-01-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0003_alter_profiljoueur_options_alter_profiljoueur_id'),
        ('tournois', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participanttournoi',
            options={'verbose_name': 'Participant Tournoi', 'verbose_name_plural': 'Participants Tournois'},
        ),
        migrations.AlterModelOptions(
            name='tournoi',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Tournoi', 'verbose_name_plural': 'Tournois'},
        ),
        migrations.AddField(
            model_name='tournoi',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du tournoi', null=True, upload_to='tournois/'),
        ),
        migrations.AddField(
            model_name='tournoi',
            name='prix_participation',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix de participation en FCFA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='participanttournoi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='participanttournoi',
            unique_together={('tournoi', 'profil')},
        ),
    ]
