# Generated by Django 6.0.1 on 2026-01-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0002_alter_participanttournoi_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanttournoi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
