# Generated by Django 6.0.1 on 2026-01-26 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0004_alter_profiljoueur_id'),
        ('tournois', '0003_alter_participanttournoi_id_alter_tournoi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanttournoi',
            name='paiement_effectue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournoi',
            name='type_tournoi',
            field=models.CharField(choices=[('solo', 'Solo'), ('duo', 'Duo'), ('escouade', 'Escouade')], default='solo', help_text='Type de tournoi (Solo, Duo ou Escouade)', max_length=10),
        ),
        migrations.AlterField(
            model_name='participanttournoi',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='profils.profiljoueur'),
        ),
        migrations.AlterField(
            model_name='participanttournoi',
            name='tournoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournois.tournoi'),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='prix_participation',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix total de participation en FCFA', max_digits=10),
        ),
        migrations.CreateModel(
            name='EquipeTournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_invitation', models.CharField(help_text="Code unique pour rejoindre l'équipe", max_length=20, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, help_text="True si l'équipe est complète")),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_creees', to='profils.profiljoueur')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='tournois.tournoi')),
            ],
            options={
                'verbose_name': 'Équipe Tournoi',
                'verbose_name_plural': 'Équipes Tournois',
            },
        ),
        migrations.AddField(
            model_name='participanttournoi',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='tournois.equipetournoi'),
        ),
    ]
