# Generated by Django 6.0.1 on 2026-01-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0004_participanttournoi_paiement_effectue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='type_tournoi',
            field=models.CharField(blank=True, choices=[('solo', 'Solo'), ('duo', 'Duo'), ('escouade', 'Escouade')], default='solo', help_text='Type de tournoi (Solo, Duo ou Escouade) - Uniquement pour Battle Royale. Multijoueur = 5 joueurs obligatoire', max_length=10, null=True),
        ),
    ]
