# Generated by Django 6.0.1 on 2026-01-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
