# Generated by Django 6.0.1 on 2026-01-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text="Image principale de l'article", null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='article',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='resume',
            field=models.TextField(blank=True, help_text="Résumé court de l'article (affiché dans la liste)", max_length=300),
        ),
    ]
