# Generated by Django 6.0.1 on 2026-01-31 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_image_article_modifie_le_article_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='layout',
            field=models.CharField(choices=[('standard', 'Standard (Texte + Images alternées)'), ('image_gauche', 'Image à gauche, Texte à droite'), ('image_droite', 'Texte à gauche, Image à droite'), ('image_centree', 'Image centrée avec texte'), ('texte_seul', 'Texte seul')], default='standard', help_text="Layout principal de l'article", max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(help_text="Introduction de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text="Image principale de l'article (pour la liste)", null=True, upload_to='articles/'),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Image pour l'article", upload_to='articles/images/')),
                ('legende', models.CharField(blank=True, help_text="Légende de l'image", max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article')),
            ],
            options={
                'verbose_name': "Image d'article",
                'verbose_name_plural': "Images d'articles",
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_block', models.CharField(choices=[('texte', 'Bloc de texte'), ('titre', 'Titre/Sous-titre'), ('image', 'Image'), ('liste', 'Liste à puces'), ('citation', 'Citation'), ('code', 'Code/Commande'), ('video', 'Vidéo (iframe)')], default='texte', max_length=20)),
                ('contenu', models.TextField(help_text='Contenu du bloc (texte, HTML, URL vidéo, etc.)')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
                ('alignement', models.CharField(choices=[('gauche', 'Gauche'), ('droite', 'Droite'), ('centre', 'Centre'), ('pleine_largeur', 'Pleine largeur')], default='pleine_largeur', help_text='Alignement du bloc', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='articles.article')),
                ('image', models.ForeignKey(blank=True, help_text='Image associée (si type = image)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.articleimage')),
            ],
            options={
                'verbose_name': "Bloc d'article",
                'verbose_name_plural': "Blocs d'articles",
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
