# Generated by Django 6.0.1 on 2026-01-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arme', models.CharField(max_length=100)),
                ('accessoires', models.JSONField()),
                ('sensibilite', models.JSONField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
