# Generated by Django 6.0.1 on 2026-01-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0001_initial'),
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profils.profiljoueur'),
        ),
    ]
