# Generated by Django 6.0.1 on 2026-01-31 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(default='fas fa-comments', help_text="Classe FontAwesome pour l'icône", max_length=50)),
                ('couleur', models.CharField(default='#FF1A1A', help_text='Couleur hexadécimale', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('nombre_posts', models.PositiveIntegerField(default=0)),
                ('nombre_membres', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Communauté',
                'verbose_name_plural': 'Communautés',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('contenu', models.TextField()),
                ('type_post', models.CharField(choices=[('texte', 'Post Texte'), ('image', 'Post Image'), ('lien', 'Post Lien')], default='texte', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='forum/posts/')),
                ('lien_url', models.URLField(blank=True, help_text="URL si type_post = 'lien'", null=True)),
                ('nombre_likes', models.PositiveIntegerField(default=0)),
                ('nombre_commentaires', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_epingle', models.BooleanField(default=False, help_text='Post épinglé en haut de la communauté')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.communaute')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-est_epingle', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_post', to='forum.post')),
            ],
            options={
                'verbose_name': 'Like Post',
                'verbose_name_plural': 'Likes Posts',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('nombre_likes', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Commentaire parent pour les réponses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='forum.commentaire')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='forum.post')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LikeCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_commentaire', to='forum.commentaire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like Commentaire',
                'verbose_name_plural': 'Likes Commentaires',
                'unique_together': {('commentaire', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='MembreCommunaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='forum.communaute')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'unique_together': {('communaute', 'utilisateur')},
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['communaute', '-date_creation'], name='forum_post_communa_f8cdfe_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['auteur', '-date_creation'], name='forum_post_auteur__d36bec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('post', 'utilisateur')},
        ),
        migrations.AddIndex(
            model_name='commentaire',
            index=models.Index(fields=['post', 'date_creation'], name='forum_comme_post_id_5acf38_idx'),
        ),
    ]
