# Generated by Django 6.0.1 on 2026-01-31 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('nouveau_commentaire', 'Nouveau commentaire sur votre post'), ('reponse_commentaire', 'Réponse à votre commentaire'), ('like_post', "Quelqu'un a aimé votre post"), ('like_commentaire', "Quelqu'un a aimé votre commentaire"), ('nouveau_post_communaute', 'Nouveau post dans votre communauté'), ('match_gagne', 'Tu as gagné un match !'), ('match_perdu', 'Tu as perdu un match'), ('tournoi_gagne', 'Tu as gagné un tournoi !'), ('nouveau_membre', 'Nouveau membre dans votre communauté')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.URLField(blank=True, help_text='Lien vers la page concernée', null=True)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='forum.commentaire')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='forum.post')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', '-date_creation', 'lu'], name='forum_notif_utilisa_6830f4_idx')],
            },
        ),
    ]
