# Generated by Django 6.0.1 on 2026-01-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilJoueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_codm', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('niveau', models.IntegerField(default=1)),
                ('rang_mj', models.CharField(max_length=50)),
                ('rang_br', models.CharField(max_length=50)),
            ],
        ),
    ]
