# Generated by Django 5.1.2 on 2026-01-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiljoueur',
            options={'verbose_name': 'Profil Joueur', 'verbose_name_plural': 'Profils Joueurs'},
        ),
        migrations.AlterField(
            model_name='profiljoueur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
