# Generated by Django 6.0.1 on 2026-01-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0004_alter_profiljoueur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiljoueur',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Image de profil', null=True, upload_to='profils/avatars/'),
        ),
    ]
