# Generated by Django 6.0.1 on 2026-01-31 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total des produits uniquement', max_digits=10)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('en_attente', 'En attente'), ('payee', 'Payée'), ('valide', 'Validé'), ('livre', 'Livré'), ('annulee', 'Annulée'), ('echec', 'Échec')], default='en_attente_paiement', max_length=20)),
                ('adresse_livraison', models.TextField()),
                ('mode_paiement', models.CharField(max_length=50)),
                ('numero_commande', models.CharField(blank=True, db_index=True, max_length=150, unique=True)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_avec_livraison', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_paystack', models.CharField(db_index=True, max_length=200, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('echec', 'Échec'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('mode_paiement', models.CharField(default='paystack', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Données supplémentaires de Paystack', null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='boutique.commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé')], default='en_cours', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boutique.panier'),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_detail', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_gros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_min_gros', models.PositiveIntegerField(default=1)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('is_active', models.BooleanField(default=True)),
                ('type_disponibilite', models.CharField(choices=[('detail', 'Détail uniquement'), ('gros', 'Gros uniquement'), ('les_deux', 'Détail et Gros')], default='les_deux', max_length=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boutique.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='PanierProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('type_commande', models.CharField(choices=[('detail', 'Détail'), ('gros', 'Gros')], max_length=10)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boutique.produit')),
            ],
        ),
    ]
