# Generated by Django 6.0.1 on 2026-02-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panierproduit',
            name='type_commande',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix_detail',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix_gros',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantite_min_gros',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='type_disponibilite',
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix normal en XOF', max_digits=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_reduit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix réduit (optionnel, pour promotions)', max_digits=10, null=True),
        ),
    ]
