# Generated by Django 6.0.1 on 2026-01-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiquesJoueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('MJ', 'Multijoueur'), ('BR', 'Battle Royale')], max_length=2)),
                ('ratio_kd', models.FloatField()),
                ('victoires', models.IntegerField()),
                ('matchs', models.IntegerField()),
                ('top10', models.IntegerField(default=0)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profils.profiljoueur')),
            ],
        ),
    ]
